"""test migration5

Revision ID: 6fef1c90e597
Revises: b4f8c9e03ca7
Create Date: 2020-05-13 21:25:42.445513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fef1c90e597'
down_revision = 'b4f8c9e03ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UC_social_id_post_id', 'association_table', ['Socials_id', 'Post_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UC_social_id_post_id', 'association_table', type_='unique')
    # ### end Alembic commands ###
