"""test migration7

Revision ID: 7fb873b047e6
Revises: b84484fcd345
Create Date: 2020-05-14 07:33:49.631792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb873b047e6'
down_revision = 'b84484fcd345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UC_social_id_post_id', 'association_table', ['Socials_id', 'Post_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UC_social_id_post_id', 'association_table', type_='unique')
    # ### end Alembic commands ###
