"""test migration8

Revision ID: 9d702d0d4cd2
Revises: 7fb873b047e6
Create Date: 2020-05-14 07:53:42.734478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d702d0d4cd2'
down_revision = '7fb873b047e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_table_Post_id_fkey', 'association_table', type_='foreignkey')
    op.drop_constraint('association_table_Socials_id_fkey', 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'socials', ['Socials_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_table', 'posts', ['Post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key('association_table_Socials_id_fkey', 'association_table', 'socials', ['Socials_id'], ['id'])
    op.create_foreign_key('association_table_Post_id_fkey', 'association_table', 'posts', ['Post_id'], ['id'])
    # ### end Alembic commands ###
