"""test migration6

Revision ID: b84484fcd345
Revises: 6fef1c90e597
Create Date: 2020-05-14 07:16:28.081177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84484fcd345'
down_revision = '6fef1c90e597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UC_social_id_post_id', 'association_table', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UC_social_id_post_id', 'association_table', ['Socials_id', 'Post_id'])
    # ### end Alembic commands ###
